name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        ruby-version: [2.4, 2.7, 3.0]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Set up caching
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-user-ruby-${{ matrix.os }}-${{matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run linter and tests for Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
      run: bundle exec rake
    - name: Report simplecov coverage
      uses: aki77/simplecov-report-action@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
